# Site settings
author: NURAN KAIRAKBAYEV
title: Nuran_K
header-img: img/home-bg.png
email: kairakbayevnuran@icloud.com
copyright_name: NURAN KAIRAKBAYEV
description: > # this means to ignore newlines until "baseurl:"
  Nuran
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  NuranKZ

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
